### ISSUE TITLE
Invalid access of closed uWS.WebSocket/SSLWebSocket.

### ISSUE THREAD

**Issue by jsandfordhughes** [soketi/soketi#169] opened 2021-11-25 13:57 UTC
We have had some issues with the server throwing these exceptions in the CLI from the server it is running from, while these errors were being thrown we had issues with clients not receiving messages. 

The client could subscribe to the channel however would not receive any messages while other clients on the same channel would. If the same client joined another channel they would be getting messages. This was completely random on what clients would receive which messages, we have since restarted the pws-server and now cannot replicate the errors again. 

Any help would be much appreciated. 

(node:3267) UnhandledPromiseRejectionWarning: Error: Invalid access of closed uWS.WebSocket/SSLWebSocket.
    at uWS.WebSocket.ws.sendJson (/usr/lib/node_modules/@soketi/pws/dist/ws-handler.js:22:20)
    at /usr/lib/node_modules/@soketi/pws/dist/ws-handler.js:44:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3267) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3267) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rennokki** [comment] 2021-11-25 14:58
This can happen if the server gets closed and somehow, a nasty message wants to be sent by your user in the server. I think this is a real bug after i checked the code again. I'm working on a fix. 🔧

**Comment by jsandfordhughes** [comment] 2021-11-25 17:20
Great, so would the bug stop messages being sent to users?

**Comment by rennokki** [comment] 2021-11-25 23:30
I assume your server hanged closing and that's why your users could access other channels but not their current ones. I need more info to help you.

- what OS are you running?
- is the app deployed as single instance or in horizontal scaling mode?
- which version of soketi caused this error?

**Comment by jsandfordhughes** [comment] 2021-11-26 11:34
- Ubuntu 20.04.3 LT
- Single instance using REDIS for the DB and DynamoDB for App
- version 0.8

Thanks

Joe

**Comment by rennokki** [comment] 2021-11-26 18:08
The issue is that for some reason, environmentally-based, your server hanged closing. What I'd recommend here, and I'll update docs regarding this thing, you should have a retry policy for sending messages.

I'll have a soft check in the app fixing message sending and communication for pending closing servers so that once the server receives any `SIG{INT,TERM,HUP}` signal, it will mark the server as pending closing, new clients won't be able to connect to the server, existing clients (while closing) cannot subscribe to new channels in the same server. Client messages and HTTP REST API interaction will still work.

You don't need Redis if you have only one instance running at any time. That's because Redis is used for inter-node comms.

**Closed** 2021-11-26 18:23 UTC
Labels: bug
